org.gradle.caching=true
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false
minecraft_version=26.2

# Gradle
loom_version=1.17-SNAPSHOT

# Fabric Properties
loader_version=0.19.3
fabric_version=0.156.0+26.2

# Mod Properties
mod_version=1.0.0
maven_group=dev.bluevista
archives_base_name=craftq3

# Dependencies
cubes_without_borders_version=4.1.0+26.2
lithium_version=mc26.2-0.25.2-fabric
no_chat_reports_version=Fabric-26.2-v2.20.2
no_chat_restrictions_version=Fabric-MC26.2-v1.2.1
replaymod_version=26.2-2.6.27
voicechat_version=2.6.20+26.2
sodium_version=mc26.2-0.9.1-fabric
worldedit_version=7.4.4