pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}
rootProject.name = 'craftq3'
include 'craftq3-core', 'craftq3-assets', 'craftq3-platform', 'craftq3-fabric'
include 'craftq3-render'
include 'craftq3-collision', 'craftq3-vm'
include 'craftq3-server'
include 'craftq3-client'
include 'craftq3-botlib'
