import dev.bluevista.craftq3.assets.fs.Pk3FileSystem;
import dev.bluevista.craftq3.botlib.chat.*;
import dev.bluevista.craftq3.botlib.chat.ChatLibrary.*;
import dev.bluevista.craftq3.botlib.script.ScriptSources;
import java.nio.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.util.*;

/** Match every original rule using generated byte strings, checking native record side effects. */
class AuditChatMatches {
  record Query(int context,String text){}
  public static void main(String[] args)throws Exception {
    Path install=Path.of("run/craftq3/games"),oracle=Path.of(".tools/chat-oracle/match-oracle");
    int matches=0,variables=0,checks=0;
    try(var fs=Pk3FileSystem.mount(install,"baseq3");var sources=new ScriptSources(fs)) {
      var library=ChatLibrary.load(sources);var matcher=new ChatMatcher(library.matches());var queries=new LinkedHashSet<Query>();
      for(var rule:library.matches()) {
        for(int variant=0;variant<8;variant++) {
          var text=new StringBuilder();
          for(var part:rule.parts()) {
            if(part instanceof Capture capture)text.append(variant%4==0?"":variant%4==1?"player"+capture.index():variant%4==2?"two words":"^1Name");
            else {var a=(Alternatives)part;text.append(a.texts().get(variant%a.texts().size()));}
          }
          String message=text.toString();if(message.length()>120)continue;
          for(String candidate:List.of(message,message.toUpperCase(Locale.ROOT),"prefix "+message,message+" suffix")) {
            if(candidate.length()>127)continue;
            queries.add(new Query(rule.context(),candidate));queries.add(new Query(0,candidate));queries.add(new Query(-1,candidate));
          }
        }
      }
      queries.add(new Query(0,"x".repeat(400)));
      var process=new ProcessBuilder(oracle.toAbsolutePath().toString(),install.resolve("baseq3/pak0.pk3").toAbsolutePath().toString()).redirectError(ProcessBuilder.Redirect.DISCARD).start();
      try(var input=process.outputWriter(StandardCharsets.US_ASCII);var output=process.inputReader(StandardCharsets.US_ASCII)) {
        if(!"READY".equals(output.readLine()))throw new AssertionError("Native chat setup failed");
        for(var query:queries) {
          var buffer=ByteBuffer.allocate(ChatMatcher.BYTE_SIZE);Arrays.fill(buffer.array(),(byte)0xab);
          boolean result=matcher.find(query.text(),query.context(),buffer,0);
          String hex=HexFormat.of().formatHex(query.text().getBytes(StandardCharsets.ISO_8859_1));
          input.write("find "+Integer.toUnsignedString(query.context())+" "+(hex.isEmpty()?"-":hex)+"\n");input.flush();
          String actual=output.readLine(),expected="MATCH "+(result?1:0)+" "+HexFormat.of().formatHex(buffer.array());
          if(!expected.equals(actual)) {
            if(actual!=null) {
              byte[] bytes=HexFormat.of().parseHex(actual.split(" ")[2]);var offsets=new ArrayList<String>();
              for(int i=0;i<bytes.length;i++)if(bytes[i]!=buffer.get(i))offsets.add(i+":"+(buffer.get(i)&255)+"/"+(bytes[i]&255));
              System.err.println("DIFFERENT "+offsets);
            }
            throw new AssertionError("query "+checks+" "+query+" javaResult="+result+" native="+(actual==null?"terminated":actual.substring(0,7)));
          }
          checks++;
          if(result) {
            matches++;
            for(int variable=0;variable<8;variable++) {
              String value=ChatMatcher.variable(buffer,0,variable,256);
              expected="VAR "+variable+" "+HexFormat.of().formatHex(value.getBytes(StandardCharsets.ISO_8859_1));actual=output.readLine();
              if(!expected.equals(actual))throw new AssertionError("Capture mismatch "+query+" variable="+variable+" expected="+expected+" actual="+actual);
              variables++;
            }
          }
        }
      }
      if(process.waitFor()!=0)throw new AssertionError("Native chat match observer failed");
    }
    System.out.printf("Chat match PASS: %,d generated queries, %,d matches, %,d capture checks; native328-byte records and results exact%n",checks,matches,variables);
  }
}
